export const ACTION_ENTER_ROOM = "ACTION_ENTER_ROOM";
export const ACTION_LEAVE_ROOM = "ACTION_LEAVE_ROOM";
export const ACTION_CHANGE_READY_STATE = "ACTION_CHANGE_READY_STATE";
export const ACTION_CREATE_GAME = "ACTION_CREATE_GAME";
export const ACTION_CONNECT_ROOM = "ACTION_CONNECT_ROOM";
export const ACTION_DISCONNECT_ROOM = "ACTION_DISCONNECT_ROOM";

export const ACTION_GAME_READY = "ACTION_GAME_READY";
export const ACTION_GAME_MURDER = "ACTION_GAME_MURDER";
export const ACTION_GAME_PROVIDE_TESTIMONIALS = "ACTION_GAME_PROVIDE_TESTIMONIALS";
export const ACTION_GAME_ADDITIONAL_TESTIMONIALS = "ACTION_GAME_ADDITIONAL_TESTIMONIALS";
export const ACTION_GAME_SOLVE_CASE = "ACTION_GAME_SOLVE_CASE";
export const ACTION_GAME_ACCOMPLICE = "ACTION_GAME_ACCOMPLICE";
export const ACTION_GAME_NEXT_SPEAKER = "ACTION_GAME_NEXT_SPEAKER";
export const ACTION_GAME_QUIT = "ACTION_GAME_QUIT";

export const BCST_UPDATE_USERS_IN_ROOM = "BCST_UPDATE_USERS_IN_ROOM";
export const BCST_CHANGE_READY_STATE = "BCST_CHANGE_READY_STATE";
export const BCST_START_GAME = "BCST_START_GAME";
export const BCST_GAME_ALL_PLAYER_READY = "BCST_GAME_ALL_PLAYER_READY";
export const BCST_GAME_STATE_UPDATE = "BCST_GAME_STATE_UPDATE";
export const BCST_GAME_DESTROYED = "BCST_GAME_DESTROYED";

